apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openwebui-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: open-webui-service
    k8s.kuboard.cn/workload: open-webui-service
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: websecure, web
    traefik.ingress.kubernetes.io/router.middlewares:
      kube-system-http-redirect-https@kubernetescrd,
      kube-system-http-redirect-https-testing@kubernetescrd,
      kube-system-common-headers@kubernetescrd

spec:
  tls:
    - hosts:
        - '*.linera-rag.respeer.ai'
        - linera-rag.respeer.ai
      secretName: linera-rag-respeer-ai-tls
  rules:
    - host: linera-rag.respeer.ai
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: open-webui-service
                port:
                  number: 8080
